import "./globals.css";
import { Montserrat } from "next/font/google";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vignan High School",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Choose the desired font weights
  variable: "--font-montserrat", // Optional: Create a CSS variable for reusability
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className={`min-h-screen ${montserrat.className}`}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
